const getFixedDeposits = `query fixedDeposit_Overview($id: Int,$status: String, $search: String, $organization_unit_id: Int, $page:Int, $size:Int, $type: String, $judge_id: Int) {
    fixedDeposit_Overview(id: $id, status: $status, judge_id: $judge_id search: $search, organization_unit_id: $organization_unit_id, page:$page, size:$size, type: $type) {
        status 
        message 
        data
        items {
            id
            id
            organization_unit{
                id
                title
            }
            subject
            judge{
                id
                title
            }
            case_number
            date_of_recipiet
            date_of_case
            date_of_finality
            date_of_enforceability
						date_of_end
            account{
                id
                title
            }
            status
            type
            file{
                id
                name 
                type
            }
            items{
                 id
                 deposit_id
                 category{
                    id
                    title
                 }
                 judge{
                    id
                    title
                 }
                 type{
                    id
                    title
                 }
                 unit
                 currency
                 case_number
                 serial_number
                 amount
                 date_of_confiscation
                 date_of_case
                 file{
                    id
                    name
                    type
                 }
                 created_at
                 updated_at
            }
            dispatches{
                id
                deposit_id
                category{
                    id
                    title
                }
                judge{
                    id
                    title
                }
                type{
                    id
                    title
                }
                unit
                currency
                case_number
                serial_number
                amount
                date_of_action
                subject
                action
                file{
                    id
                    name
                    type
                }
                created_at
                updated_at
            }
            judges{
                id
                deposit_id
                will_id
                judge{
                    id
                    title
                }
                date_of_start
                date_of_end
                file{
                    id
                    name
                    type
                }
                created_at
                updated_at
            }
            created_at
            updated_at   
        }
        }
    }`;

export default getFixedDeposits;
