const getWill = `query fixedDepositWill_Overview($id: Int,$status: String, $search: String, $organization_unit_id: Int, $page:Int, $size:Int) {
    fixedDepositWill_Overview(id: $id, status: $status,  search: $search, organization_unit_id: $organization_unit_id, page:$page, size:$size) {
        status 
        message 
        data
        items {
             id
            organization_unit{
                id
                title
            }
            subject
            father_name
            date_of_birth
            jmbg
            case_number_si
            case_number_rs
            date_of_receipt_rs
            date_of_receipt_si
            date_of_end
            status
            description
            file{
                id
                name
                type
            }
            dispatches{
                id
                will_id
                dispatch_type
                judge{
                    id
                    title
                }
                case_number
                date_of_dispatch
                date_of_case
                file{
                    id
                    name
                    type
                }
                created_at
                updated_at
            }
            judges{
                id
                deposit_id
                will_id
                judge{
                    id
                    title
                }
                date_of_start
                date_of_end
                file{
                    id
                    name
                    type
                }
                created_at
                updated_at
            }
            created_at
            updated_at   
        }
        }
    }`;

export default getWill;
