const getInvoice = `query invoiceOverview($id: Int, $year: Int, $supplier_id: Int, $status: String, $search: String, $organization_unit_id: Int, $page:Int, $size:Int, $type: String) {
    invoice_Overview(id: $id, status: $status, year: $year, supplier_id: $supplier_id, search: $search, organization_unit_id: $organization_unit_id, page:$page, size:$size, type: $type) {
        message
        total
        items {
            id
            status
            type
            net_price
            vat_price
            type_of_contract{
                id
                title
            }
            type_of_subject{
                id
                title
            }
            source_of_funding{
                id
                title
            }
            tax_authority_codebook{
                id
                title
            }
            invoice_number
            supplier_title
            supplier{
                id
                title
            }
            order_id
            order{
                id
                title
            }
            organization_unit{
                id
                title
            }
            date_of_invoice
            pro_forma_invoice_date
            pro_forma_invoice_number
            receipt_date
            sss_invoice_receipt_date
            date_of_payment
            date_of_start
            file{
                id
                name
                type
            }
            pro_forma_invoice_file{
                id
                name
                type
            }
            bank_account
            description
            is_invoice
            articles{
                id
                title
                net_price
                vat_price
                vat_percentage
                description
                amount
                account{
                    id
                    title
                }
                cost_account{
                    id
                    title
                }
            }
            additional_expenses{
                id
                title
                price
                bank_account
                subject{
                    id
                    title
                }
                account{
                    id
                    title
                }
            }
        }
    }
}`;

export default getInvoice;
