const salariesOverview = `query salary_Overview($id: Int, $month: String, $organization_unit_id: Int, $page:Int, $size:Int, $year: Int, $activity_id: Int) {
    salary_Overview(id: $id, activity_id: $activity_id, month: $month, organization_unit_id: $organization_unit_id, page:$page, size:$size, year: $year) {
        status 
        message 
        data
        items {
            id
            organization_unit{
                id
                title
            }
            activity{
                id
                title
            }
            month
            registred
            is_deletable
            number_of_employees
            date_of_calculation
            description
            status
            gross_price
            vat_price
            net_price
            obligations_price
            account{
                id
                title
            }
            account_amounts{ 
                id
                account
                amount
            }
            salary_additional_expenses{
                id
                title
                organization_unit{
                    id
                    title
                }
                activity{
                    id
                    title
                }
                account{
                    id
                    title
                }
                amount
                subject{
                    id
                    title
                }
                debtor{
                    id
                    title
                }
                status
                bank_account
                type
                created_at
                updated_at
            }
            created_at
            updated_at 
        }
        }
    }`;

export default salariesOverview;
