const enforcedPaymentOverview = `query enforcedPayment_Overview($id: Int,$status: String, $search: String, $organization_unit_id: Int, $page:Int, $size:Int, $registred: Boolean) {
    enforcedPayment_Overview(id: $id, status: $status, search: $search, organization_unit_id: $organization_unit_id, page:$page, size:$size, registred:$registred) {
        status 
        message 
        data
        total
        items {
            id
            organization_unit{
                id
                title
            }
            supplier{
                id
                title
            }
            agent{
                id
                title
            }
            amount
            amount_for_lawyer
		    amount_for_agent
            amount_for_bank
            account_for_expenses{
                id
                title
            }
            execution_number
            bank_account
            date_of_payment
            date_of_sap
            description
            id_of_statement
            sap_id
            status
            file{
                id
                name
                type
            }
             return_file{
                id
                name
                type
            }
			return_date
            return_amount
            items{
                 id
                 invoice_id
                 account{
                    id
                    title
                 }
                 amount
                 title
            }
            created_at
            updated_at
        }
        }
    }`;

export default enforcedPaymentOverview;
