const accountingEntryOverview = `query accountingEntry_Overview($id: Int, $organization_unit_id: Int, $page:Int, $size:Int, $type: String) {
   accountingEntry_Overview(id: $id organization_unit_id: $organization_unit_id, page:$page, size:$size, type: $type) {
       status 
       message 
       data
       items {
           id
           organization_unit{
                   id
                   title
                  address
           }
           date_of_booking
           type
           debit_amount
           credit_amount  
           formated_id_of_entry
           items{
                id
                title
                account{
                   id
                   title
                }
                debit_amount
                credit_amount  
                title
                type
                date
                invoice{
                   id
                   title
                }
                salary{
                   id
                   title
                }
                return_enforced_payment{
                  id
                  title
                }
                payment_order{
                   id
                   title
                }
                supplier{
                  id
                  title
               }
                enforced_payment{
                   id
                   title
                }
           }        
       }
       }
   }`;

export default accountingEntryOverview;
