const accountingEntryOverview = `query accountingEntry_Overview($id: Int, $organization_unit_id: Int, $page:Int, $size:Int, $type: String, $date_of_start: String, $date_of_end: String, $group: Boolean, $sort_for_report: Boolean) {
    accountingEntry_Overview(id: $id organization_unit_id: $organization_unit_id, page:$page, size:$size, type: $type, date_of_start: $date_of_start, date_of_end: $date_of_end, group: $group, sort_for_report: $sort_for_report) {
        status 
        message 
        data
        sorted_items{
                 id
                 title
                 entry_number
                 entry_date
                 account{
                    id
                    title
                 }
                 debit_amount
                 credit_amount  
                 title
                 type
                 date
                 invoice{
                    id
                    title
                 }
                 salary{
                    id
                    title
                 }
                 payment_order{
                    id
                    title
                 }
                 enforced_payment{
                    id
                    title
                 }
                 return_enforced_payment{
                    id
                    title
                 }
            } 
        items {
            id
            organization_unit{
                    id
                    title
                    address
            }
            date_of_booking
            debit_amount
            credit_amount  
            id_of_entry
            formated_id_of_entry
            items{
                 id
                 title
                 entry_number
                 entry_date
                 account{
                    id
                    title
                 }
                 debit_amount
                 credit_amount  
                 title
                 type
                 date
                 invoice{
                    id
                    title
                 }
                 salary{
                    id
                    title
                 }
                 payment_order{
                    id
                    title
                 }
                 enforced_payment{
                    id
                    title
                 }
                 return_enforced_payment{
                    id
                    title
                 }
            }        
        } 
    }
  }`;

export default accountingEntryOverview;
